serial.redirectToUSB()
envirobit.setLEDs(1)

basic.forever(() => { 
    serial.writeNumber(envirobit.getBME280ChipID())
    serial.writeString(" T: ")
    serial.writeNumber(envirobit.getTemperature())
    serial.writeString(" P:")
    serial.writeNumber(envirobit.getPressure())
    serial.writeString(" H:")
    serial.writeNumber(envirobit.getHumidity())
    serial.writeString(" R:")
    serial.writeNumber(envirobit.getRed())
    serial.writeString(" G:")
    serial.writeNumber(envirobit.getGreen())
    serial.writeString(" B:")
    serial.writeNumber(envirobit.getBlue())
    serial.writeLine("")
    control.waitMicros(500000)
})